version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_segundocorte
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock   # ðŸ”¹ Clave: asÃ­ sÃ­ funciona en Docker Desktop (Windows)
      - /usr/bin/docker:/usr/bin/docker              # Para que Jenkins use el cliente Docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_GROUP_ID=0
    restart: unless-stopped

  app:
    build:
      context: ./2fa-nodejs
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "file:./prisma/dev.db"
    volumes:
      - ./2fa-nodejs:/app
      - /app/node_modules
    command: yarn start

volumes:
  jenkins_data:
